Fix a bug in #23.
Endilll/vapoursynth-preview pull request #25
Opened 2021-04-26 07:29 UTC by SaltyChiang

Fix the issue referred here: https://github.com/Endilll/vapoursynth-preview/pull/23#issuecomment-826439141

2021-04-26 12:01 UTC, Ichunjo commented
It seems to work but when reloading, the checkbox "Sync Outputs" is always disabling.

2021-04-26 12:21 UTC, SaltyChiang commented
> It seems to work but when reloading, the checkbox "Sync Outputs" is always disabled itself.

Fixed.
Thanks for pointing out the problem.

2021-04-29 19:15 UTC, Endilll requested changes

2021-04-29 19:15 UTC, Endilll commented on vspreview/core/abstracts.py
> +                self.toggle_button.click()
why not simply `self.toggle_button.setChecked(toggle)`?

2021-04-29 19:15 UTC, Endilll commented on vspreview/main.py
> +    SYNC_OUTPUTS              = False
this constant should also be used when sync_output checkbox is created

2021-04-30 02:55 UTC, SaltyChiang commented on vspreview/core/abstracts.py
> +                self.toggle_button.click()
Just set the button checked will not toggle the toolbar.
In fact, this operation will just make the button pressed without any other effect.

2021-04-30 03:05 UTC, SaltyChiang commented on vspreview/main.py
> +    SYNC_OUTPUTS              = False
Done.

2021-04-30 09:32 UTC, Endilll commented on vspreview/core/abstracts.py
> +                self.toggle_button.click()
what about `if self.toggle_button.isChecked() != toggle:` then? to make it work both ways

2021-04-30 10:09 UTC, SaltyChiang commented on vspreview/core/abstracts.py
> +                self.toggle_button.click()
Well, that's a bit subtle.
Imagine that for a toolbar, `toggle == False` (in the YAML file) but the `toggle_button` is checked, with autosave checkbox unchecked:
when you reload script, the parameter in the YAML file will not change and this toolbar will be set to invisible. 
Changing the toolbar layout when reloading shouldn't be a good idea for users.

2021-04-30 10:15 UTC, SaltyChiang commented on vspreview/core/abstracts.py
> +                self.toggle_button.click()
There exists an assumption: the toolbars are always invisible when they are created. And the code ensures this.
Maybe `if not self.toggle_button.isChecked() and toggle:` is acceptable.

2021-05-27 15:56 UTC, Endilll approved these changes

2021-05-27 15:57 UTC, merged