Allow -f/--frame CLI arg to seek to frame on load
Endilll/vapoursynth-preview pull request #34
Opened 2021-08-06 20:58 UTC by shssoichiro

Closes #33

2021-08-07 07:40 UTC, Endilll requested changes
One of the comments may be hard to address, so If it woks for you, you can use your fork for now, until I find time to implement it as I see fit

2021-08-07 07:40 UTC, Endilll commented on vspreview/core/abstracts.py
> +    def load_script(self, script_path: Path, external_args: str = '', reloading = False, start_frame: int = 0) -> None:
if it's a frame, we should expect Frame type here, not int

2021-08-07 07:40 UTC, Endilll commented on vspreview/main.py
> +            self.toolbars.main.frame_control.setValue(Frame(start_frame))
`setValue` feels like a hack. I doubt it should be done this way

2021-08-07 15:51 UTC, shssoichiro commented on vspreview/main.py
> +            self.toolbars.main.frame_control.setValue(Frame(start_frame))
What would be a better way? I'm not particularly familiar with the codebase.

2021-08-07 15:59 UTC, Endilll commented on vspreview/main.py
> +            self.toolbars.main.frame_control.setValue(Frame(start_frame))
`switch_frame()`, but I'm not sure it'll work properly this early.
we also need to make sure we're doing good with respect to storage loading

2021-08-07 16:01 UTC, Endilll commented
One more thing I that slipped my mind is that we are not single-output preview, so we should also accept index of the output or its name (not sure about this one) in CLI

2021-08-15 20:40 UTC, shssoichiro commented on vspreview/main.py
> +            self.toolbars.main.frame_control.setValue(Frame(start_frame))
`switch_frame` works, if it's the first time loading a specific file. If it's been loaded before, then the saved frame position overrides the `switch_frame` call. (I don't think this is specific to `switch_frame`, but I couldn't trace exactly where this was happening--only that it's happening in `switch_output`, and that load of the saved frame gets called twice, but the only place I see `switch_output` called is right before `switch_frame`)

2021-08-15 20:41 UTC, shssoichiro commented on vspreview/core/abstracts.py
> +    def load_script(self, script_path: Path, external_args: str = '', reloading = False, start_frame: int = 0) -> None:
I attempted this but got a weird cyclical import error. `ImportError: cannot import name 'Time' from partially initialized module 'vspreview.core' (most likely due to a circular import) (/home/soichiro/repos/vapoursynth-preview/vspreview/core/__init__.py)`

2021-08-16 16:02 UTC, Endilll commented on vspreview/core/abstracts.py
> +    def load_script(self, script_path: Path, external_args: str = '', reloading = False, start_frame: int = 0) -> None:
I can reproduce this on my machine as well. One more thing for me to look into then.

2021-08-16 16:06 UTC, Endilll commented on vspreview/main.py
> +            self.toolbars.main.frame_control.setValue(Frame(start_frame))
Thanks for looking into this. I think the fact that `start_frame` doesn't work on script reload as actually a feature, because in this case user would expect to stay at the same frame he was.

2022-04-20 06:32 UTC, closed without merging